version: '3'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - skynet-s3
      - skynet
networks:
  skynet-s3:
    name: "skynet-s3"
  skynet:
    name: "skynet"
#  default:
#    external:
#      name: "skynet"

#  skynet:
#  default:
#    external:
#      name: dictionary-db_skynet