version: '3'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
#    networks:
#      - skynet
networks:
  default:
    external:
      name: "skynet"
#  skynet:
#  default:
#    external:
#      name: dictionary-db_skynet